### ISSUE TITLE
How should this be run on Linux

### ISSUE THREAD

**Issue by jwsmite** [DJATOM/avs2yuv#2]
Hi, how is this meant to work on posix like OSes? when I run avs2yuv (linux build) I get "Error: failed to load avisynth.dll."

**Comment by DJATOM** [comment]
Looks like your Avisynth+ installation unreachable by avs2yuv. 
Try to build it from sources. If compiler emits error about headers, most likely you don't have avs+ installed.

**Comment by jwsmite** [comment]
Awesome, thanks for swift reply, yeh that was all it took, instructions here to install avisynth+ for the next guy who struggles to find their way through: https://github.com/AviSynth/AviSynthPlus/blob/master/distrib/docs/english/source/avisynthdoc/contributing/posix.rst#ubuntu-19-10-or-higher
