### ISSUE TITLE
Error: unsupported colorspace on Linux

### ISSUE THREAD

**Issue by sosie-js** [DJATOM/avs2yuv#3]
Hello DJATOM,

Under Linux, I am stuck with `Error: unsupported colorspace.` message
when I trigger avs2yuv -on AviSynth+  examples such as Audio:
`avs2yuv  AviSynth+/Examples/Audio.avs  -`
I get:
`Avs2YUV 0.29
Script file:	AviSynth+/Examples/Audio.avs
Resolution:	320x240
Frames per sec:	30000/1001 (29.970)
Total frames:	107892
**Error: unsupported colorspace.**
` 
to behind it can not be pipelined to mpv or else.

WHEREAS DIRECTLY `mpv AviSynth+/Examples/Audio.avs` works and indicates
 (+) Video --vid=1 (rawvideo 320x240 29.970fps)
Seems there is in fact no colorspace at all, I though Output format is yuv4mpeg by default and not raw.

Any Clue?

**Comment by DJATOM** [comment]
Post your script?

**Comment by DJATOM** [comment]
Ah, found it in examples, so it's `rgb32`. You can't encapsulate `rgb32` into `y4m` container, your file will end-up unusable. Yet I can lax format check for `raw` mode (you will have to load resulted file manually - pointing all metadata for reader). 

The purpose of application is piping `yuv` clips into encoders. `rgb` format generally inefficient for compression, so it mostly not applicable for the task.

**Comment by DJATOM** [comment]
> Yet I can lax format check for `raw` mode

Done.

**Comment by sosie-js** [comment]
Well, even if it goes then further, both mpv, ffplay did not recognize your raw format
avs2yuv -raw Audio.avs -| mpv -      gives Failed to recognize file format.
avs2yuv -raw Audio.avs -| ffplay -i -   gives  pipe:: Invalid data found when processing input2:40

**Comment by DJATOM** [comment]
Indeed. You must add every metadata "by hand" and note ffplay or mpv that you're importing raw data.

**Comment by sosie-js** [comment]
avs2yuv -raw Audio.avs -| mpv --demuxer=rawvideo --demuxer-rawvideo-w=320 --demuxer-rawvideo-h=240 --demuxer-rawvideo-fps=29.970 - does not render video correctly, I mean I have a video unsynchronized

**Comment by DJATOM** [comment]
Well then, I dont know what causing synchronization issue. It should output frames serially. In fact avs2yuv doesn't support audio, maybe you're facing desynchronization for that reason...

**Comment by sosie-js** [comment]
Thnks for pointing that out. ,  I tried to set up with --demuxer-rawvideo-mp-format=rgb32, video is garbled
For now, whatever I do , with vapoursynth too, only the sound working combination is mpv direct way without piping. Remains the combination however to to it with wine or better playonlinux, the wine helper.. (that I want to get rid of now hoping avynsynth+ on linux will do the job)

**Comment by sosie-js** [comment]
I have the same message Error: unsupported colorspace even if I add ConvertToYUY2() at the end of avs, so I is in fact not related to colorspace imho

**Comment by DJATOM** [comment]
Apparently yuy2 cannot be encapsulated into y4m, but yv16 should work.

**Comment by sosie-js** [comment]
I got black screen with ConvertToYV16() due to libvdpau-va-gl: VideoSurface::PutBitsYCbCr_glsl(): not implemented source YCbCr format 'VDP_YCBCR_FORMAT_UYVY'

WITH ConvertToYUV420() APPENDED TO Audio.avs
` avs2yuv AviSynthPlus/Examples/Audio.avs  - | mpv - ` WORKS!!!

IN the Authors examples as we have the video parameter
video=ConvertToYUV420(video)  WORKS.
(I have `Error converting utf8 string to wi` like with mpv in direct however)

**Comment by DJATOM** [comment]
There's no special handling of utf8 path, so you might have a problem importing that. 
I suggest to use English names in your project/script path.

**Comment by sosie-js** [comment]
I didn't choose the name of the authors of the script serving as test
https://github.com/AviSynth/AviSynthPlus/blob/master/distrib/Examples/Authors.avs

**Comment by sosie-js** [comment]
Hey DJATOM did you know qyot27? I would suggest to get closer to him
I fall on his page putting comments on your project and starting to force to YuV420 even the Version: `echo Version\(\).ConvertToYUV420\(\)>test.avs`

See https://discuss.haiku-os.org/t/avisynth-scripting-nle-frameserver/10086/7

**Comment by sosie-js** [comment]
ISSUE SOLVED
