### ISSUE TITLE
About audio support

### ISSUE THREAD

**Issue by sosie-js** [DJATOM/avs2yuv#4]
'To get access to both RGB formats and audio, you’ll need a build of FFmpeg that accepts AviSynth scripts as input.'  from our friend qyot27
---

So I wondered if we can not wrap your tool with ffmpeg using the cool
https://framagit.org/ericb/ffmpeg-cpp2

```
git clone https://framagit.org/ericb/ffmpeg-cpp2
cd ffmpeg-cpp2
cat 'install(TARGETS ${PROJECT_NAME} ARCHIVE DESTINATION /usr/local/lib )' >> CMakeLists.txt
mkdir ffmpeg-ccp2-build
cd ffmpeg-ccp2-build
cmake ../ -G Ninja 
ninja
sudo ninja install 
```
this will generate  /usr/local/lib/libffmpeg-cpp.a

then you can inspirate from demos/

**Comment by DJATOM** [comment]
For avs2yuv it's definitely out of scope. This program intended for working with video. Maybe https://github.com/chikuzen/avs2pipemod might be good piece of code for you.

**Comment by sosie-js** [comment]
ssems for windoze, no doc, abandonned. thanks for your reply.
